services:
  kabasalt:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}

    # for interactive mode e.g. for entrypoint /bin/shell
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    entrypoint: "/bin/bash"

    # Specifying an init process ensures the usual responsibilities of an init system,
    # such as reaping zombie processes, are performed inside the created container.
    # https://docs.docker.com/engine/reference/run/#specify-an-init-process
    init: true

    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
    ports:
      - ${PORT}:9999
    volumes:
      - type: volume
        source: ka-basalt-2022-datadownloader_data
        target: /home/aicrowd/data/

volumes:
  ka-basalt-2022-datadownloader_data:
    external: true