services:
  kabasalt:
    image: kabasalt
    container_name: ${CONTAINER_NAME}

    # Specifying an init process ensures the usual responsibilities of an init system,
    # such as reaping zombie processes, are performed inside the created container.
    # https://docs.docker.com/engine/reference/run/#specify-an-init-process
    init: true

    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
    entrypoint: /bin/bash
    ports:
      - 9999:9999
    volumes:
      - type: volume
        source: ka-basalt-2022-datadownloader_data
        target: /home/aicrowd/data/

volumes:
  ka-basalt-2022-datadownloader_data:
    external: true