services:
  kabasalt:
    image: kabasalt_laurito
    container_name: basalt_container_laurito

    # for interactive mode e.g. for entrypoint /bin/shell
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    entrypoint: "/bin/bash"

    # Specifying an init process ensures the usual responsibilities of an init system,
    # such as reaping zombie processes, are performed inside the created container.
    # https://docs.docker.com/engine/reference/run/#specify-an-init-process
    init: true

    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
    ports:
      - 9898:9999
    volumes:
      - type: volume
        source: ka-basalt-2022-datadownloader_data
        target: /home/aicrowd/data/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # specify the device ids of your system's GPUs in docker-compose.override.yaml. The specified GPUs will be used for training.
              capabilities: [ gpu ]
volumes:
  ka-basalt-2022-datadownloader_data:
    external: true