name: minerl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.0
  - pip:
    - minerl
    - coloredlogs
    - matplotlib
    - aicrowd-api
    - aicrowd-gym

