name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - py-opencv
  - pip:
    - git+https://github.com/minerllabs/minerl
    - matplotlib
    - coloredlogs
    - aicrowd-api
    - aicrowd-gym
    - gym3
    - attrs
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - torch==1.12.1+cu113
    - werkzeug==2.1
    - git+https://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@github.com/BASALT-2022-Karlsruhe/imitation.git