name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - wandb
  - py-opencv
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - pip:
    - git+https://github.com/minerllabs/minerl
    - matplotlib
    - tqdm
    - coloredlogs
    - aicrowd-api
    - aicrowd-gym
    - gym3
    - attrs
    - werkzeug==2.1
    - git+https://github.com/rk1a/imitation.git@human-preferences
    - opencv-python-headless
    - django
    - djangorestframework
