name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    - aicrowd-api
    - aicrowd-gym
    - gym3
    - attrs
    - git+https://${GIT_ACCESS_TOKEN}@github.com/BASALT-2022-Karlsruhe/imitation.git
